from 0 to 1
TERM_PROGRAM=vscode
TERM=prikol
HOMEBREW_TEMP=/tmp/dnicki/Homebrew/Temp
SHELL=/bin/zsh
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.z4BZZyQVZE/Render
TERM_PROGRAM_VERSION=1.57.1
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
ZSH=/Users/dnicki/.oh-my-zsh
USER=dnicki
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.eyUG8wWjbK/Listeners
__CF_USER_TEXT_ENCODING=0x3956:0x0:0x0
PAGER=less
HOMEBREW_CACHE=/tmp/dnicki/Homebrew/Caches
LSCOLORS=Gxfxcxdxbxegedabagacad
PATH=/Users/dnicki/goinfre/anaconda/bin:/Users/dnicki/.brew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/Users/dnicki/goinfre/anaconda/bin:/Users/dnicki/.brew/bin
PWD=/Users/dnicki/minicpy
LANG=en_US.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=2
HOME=/Users/dnicki
VSCODE_GIT_ASKPASS_MAIN=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js
LESS=-R
LOGNAME=dnicki
VSCODE_GIT_IPC_HANDLE=/var/folders/zz/zyxvpxvq6csfxvn_n0001s_r000f_p/T/vscode-git-7ee2787a0c.sock
VSCODE_GIT_ASKPASS_NODE=/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)
GIT_ASKPASS=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh
COLORTERM=truecolor
_=HERE
